spring:
  config:
    import: optional:file:.env[.properties]   # .env 로드
  profiles:
    active: local
app:
  mail:
    from: "박정훈 <${MAIL_USERNAME}>"

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-ms: ${JWT_AT_MS}
  refresh-token-validity-ms: ${JWT_RT_MS}
